export const HUNGARIAN_ALPHABET = [
  {
    letter: "A",
    name: "a",
    pronunciation: "Like 'o' in 'hot,' only drop your chin.",
    example: "hal (fish)",
  },
  {
    letter: "Á",
    name: "á",
    pronunciation: "Long, like 'a' in 'father'.",
    example: "hát (back)",
  },
  {
    letter: "B",
    name: "bé",
    pronunciation: "Like English 'b'.",
    example: "bor (wine)",
  },
  {
    letter: "C",
    name: "cé",
    pronunciation: "Like 'ts' in 'hats'.",
    example: "cica (cat)",
  },
  {
    letter: "CS",
    name: "csé",
    pronunciation: "Like 'ch' in 'teacher'.",
    example: "csak (only)",
  },
  {
    letter: "D",
    name: "dé",
    pronunciation: "Like English 'd'.",
    example: "de (but)",
  },
  {
    letter: "DZ",
    name: "dzé",
    pronunciation: "Like 'ds' in 'kids'.",
    example: "edzés (training)",
  },
  {
    letter: "DZS",
    name: "dzsé",
    pronunciation: "Like 'j' in 'jam'.",
    example: "dzsungel (jungle)",
  },
  {
    letter: "E",
    name: "e",
    pronunciation: "Short, like 'e' in 'get'.",
    example: "egy (one)",
  },
  {
    letter: "É",
    name: "é",
    pronunciation: "Long, like 'ay' in 'say'.",
    example: "és (and)",
  },
  {
    letter: "F",
    name: "ef",
    pronunciation: "Like English 'f'.",
    example: "fa (tree)",
  },
  {
    letter: "G",
    name: "gé",
    pronunciation: "Always hard, like 'g' in 'go'.",
    example: "gép (machine)",
  },
  {
    letter: "GY",
    name: "gyé",
    pronunciation: "Soft 'd' sound, like 'd' in 'during'.",
    example: "gyár (factory)",
  },
  {
    letter: "H",
    name: "há",
    pronunciation: "Like English 'h'.",
    example: "ház (house)",
  },
  {
    letter: "I",
    name: "i",
    pronunciation: "Short, like 'i' in 'it'.",
    example: "itt (here)",
  },
  {
    letter: "Í",
    name: "í",
    pronunciation: "Long, like 'ee' in 'see'.",
    example: "íz (taste)",
  },
  {
    letter: "J",
    name: "jé / elipszilon",
    pronunciation: "Like 'y' in 'you'.",
    example: "jó (good)",
  },
  {
    letter: "K",
    name: "ká",
    pronunciation: "Like English 'k'.",
    example: "kék (blue)",
  },
  {
    letter: "L",
    name: "el",
    pronunciation: "Like English 'l'.",
    example: "ló (horse)",
  },
  {
    letter: "LY",
    name: "elipszilon",
    pronunciation: "Like 'y' in 'you'.",
    example: "hely (place)",
  },
  {
    letter: "NY",
    name: "eny",
    pronunciation: "Like 'ny' in 'canyon'.",
    example: "anya (mother)",
  },
  {
    letter: "O",
    name: "o",
    pronunciation: "Short, rounded 'o' like 'or'.",
    example: "orr (nose)",
  },
  {
    letter: "Ó",
    name: "ó",
    pronunciation: "Long 'o' like 'go'.",
    example: "óra (hour)",
  },
  {
    letter: "Ö",
    name: "ö",
    pronunciation: "Like 'u' in 'burn'.",
    example: "öt (five)",
  },
  {
    letter: "Ő",
    name: "ő",
    pronunciation: "Longer version of 'Ö'.",
    example: "ő (he/she)",
  },
  {
    letter: "P",
    name: "pé",
    pronunciation: "Like English 'p'.",
    example: "apa (father)",
  },
  {
    letter: "R",
    name: "er",
    pronunciation: "Rolled 'r', like in Spanish.",
    example: "régi (old)",
  },
  {
    letter: "S",
    name: "es",
    pronunciation: "Like 'sh' in 'ship'.",
    example: "sós (salty)",
  },
  {
    letter: "SZ",
    name: "esz",
    pronunciation: "Like English 's' in 'sea'.",
    example: "szép (beautiful)",
  },
  {
    letter: "T",
    name: "té",
    pronunciation: "Like English 't'.",
    example: "tó (lake)",
  },
  {
    letter: "TY",
    name: "tyé",
    pronunciation: "Soft 't' sound, like 't' in 'steward'.",
    example: "tyúk (hen)",
  },
  {
    letter: "U",
    name: "u",
    pronunciation: "Like 'u' in 'put,' only round your lips.",
    example: "fut (run)",
  },
  {
    letter: "Ú",
    name: "ú",
    pronunciation: "Long, like 'oo' in 'moon'.",
    example: "út (road)",
  },
  {
    letter: "Ü",
    name: "ü",
    pronunciation: "Say 'i' like in 'sit,' purse your lips and put your tongue forward.",
    example: "ül (sit)",
  },
  {
    letter: "Ű",
    name: "ű",
    pronunciation: "Longer version of 'Ü'.",
    example: "tűz (fire)",
  },
  {
    letter: "V",
    name: "vé",
    pronunciation: "Like English 'v'.",
    example: "víz (water)",
  },
  {
    letter: "Z",
    name: "zé",
    pronunciation: "Like English 'z'.",
    example: "zár (close)",
  },
  {
    letter: "ZS",
    name: "zsé",
    pronunciation: "Like 's' in 'pleasure'.",
    example: "zseb (pocket)",
  },
];
