create table public.phrasebook_entries (
  id bigint generated by default as identity primary key,
  hungarian text not null,
  english text not null,
  created_at timestamptz not null default now(),
  unique (hungarian, english)
);

alter table public.phrasebook_entries enable row level security;

grant select, insert, update, delete on table public.phrasebook_entries to anon, authenticated;
grant usage, select on sequence public.phrasebook_entries_id_seq to anon, authenticated;

create policy "Phrasebook entries are shared"
on public.phrasebook_entries
for all
to anon, authenticated
using (true)
with check (true);
